name: Sunay Lint

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM + Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17"

      - name: Install Ninja
        run: choco install ninja

      - name: Configure
        run: cmake -B build -S . -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        shell: bash
        run: |
          clang-tidy -p build $(git ls-files '*.cpp')
