name: Sunay Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@v3

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sunay-Windows
          path: build/Release
